### ISSUE TITLE
Routing issues after deploy

### ISSUE THREAD

**Issue by stursby** [nuxt/express#1]
So I cloned this template (didn't change any code) and deployed via [`now`](https://zeit.co/now/) to here --> [https://nuxt-express-dmdndmadiv.now.sh](https://nuxt-express-dmdndmadiv.now.sh).

This could just be my misunderstanding of how `express` / `nuxt` work together, but the `<nuxt-link>`s never work as it looks to be trying to load the `/api` route(s) via localhost:3000.

![image](https://cloud.githubusercontent.com/assets/527849/22487625/b86979ac-e7d3-11e6-9ba6-a3233f35cfc4.png)

But, a full page refresh on user 0 [https://nuxt-express-dmdndmadiv.now.sh/0](https://nuxt-express-dmdndmadiv.now.sh/0) works just fine.

Could this be an `axios` issue too?

**Comment by Atinux** [comment]
Hi @stursby 

Indeed it's due of `axios` on the client-side since it has to know the full url.

Since you are deploying on `now`, you need to set the BASE_URL environment variable when deploying:
```bash
now -e BASE_URL=https://nuxt-express.now.sh
```

Then you need to set the alias with `now alias set ...`.

Otherwise, if you want to use the generated url from now, replace in your nuxt.config.js `process.env.BASE_URL` by `process.env.NOW_URL`  (but you won't be able to set a custom alias).

**Comment by stursby** [comment]
Awesome 👍 That totally worked... aliased that URL too --> https://nuxt-express.now.sh/

**Comment by Atinux** [comment]
🙌

**Comment by Atinux** [comment]
@stursby `BASE_URL` has been removed since I found an easier way: https://github.com/nuxt/express/commit/95a9867b1108777932779c4fc46ef0a0522811b5

Indeed, the localhost url works on the server but not on the client when deployed on a real server.
