### ISSUE TITLE
Guide on handling protected SSR api requests #334

### ISSUE THREAD

**Issue by alexchopin** [nuxt/express#14]
https://github.com/nuxt/nuxt.js/issues/334

**Comment by uptownhr** [comment]
Should I to the template or create a guide? Where is a good place to write the guide?

**Comment by alexchopin** [comment]
I think it could be nice to have it on the README.md of this repo.
You can do a PR 👍

**Comment by uptownhr** [comment]
@alexchopin So I took some time to take a crack at this today and I honestly believe there is a problem on acheiving protected routes from the SSR. Like I've mentioned below, there are work arounds, but to achieve a clean and simple solution the context need to be available to the plugin. 

Here's my axios plugin for example,

``` 
import axios from 'axios'
import debug from 'debug'

debug('bambee:nuxt')('axios plugin')

if (!process.BROWSER_BUILD) {
  axios.defaults.baseURL = 'http://api:3000'
} else {
  axios.defaults.baseURL = '/api'
}
```
In my project, I use a proxy api end point that hydrates the user's token from the session.
server.js

```
app.use('/api', async (req, res) => {
  if (!req.session.user) return res.status(401).send('not authorized')

  try {
    let response = await api(req.path, req.body, { method: req.method, token: req.session.user.token } )
    res.send(response.data)
  } catch (e) {
    if (e && e.response) return res.status(e.response.status).send(e.response.statusText)

    apiDebug({
      e,
      request: {
        path: req.path,
        body: req.body
      }
    })
    return res.status(500).send(e)
  }
})
```

This was fine for my project because I have multiple microservices that all rely on the api. 

For a simple starter project though, best case would be to not need a proxy that hydrates the user session/token. 

something like: 

plugins/axios.js
```
module.exports = function (context) {
  if (!process.BROWSER_BUILD) {
  axios.defaults.baseURL = 'http://api:3000'
  axios.headers = {
     cookie: req.cookie,
    ...
  }
 }
}
```
Not really sure what the cookie headers are but just an example. 

Maybe I'm thinking about this the wrong way but would love to hear thoughts and suggestions.

**Comment by alexchopin** [comment]
What about using a global middleware (in nuxt.config.js) to setup axios.headers?

**Comment by uptownhr** [comment]
I think that can work, is there a different bind than router that is more suitable in this case?
